CREATE TABLE webshare_keys (
    id VARCHAR(50) PRIMARY KEY,
    api_key VARCHAR(255) UNIQUE NOT NULL,
    label VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
