CREATE TABLE IF NOT EXISTS facebook_posted_articles (
    article_id VARCHAR(255) PRIMARY KEY REFERENCES articles(id) ON DELETE CASCADE,
    fb_post_id VARCHAR(255) NOT NULL,
    posted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
